# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d745d3a4948208ed4ceb4dbd88ab9e25ff04b078197a13ab5aad4904cee967ed3b3372f21256eadc81411a310b92a4fdd821d4d786a02ab4ed792614014300d

test:
  secret_key_base: 47d96c29b6a162b40dfb448395a83e822dfed61be22a12dc46d845be599d8ad96b6652ddcf297e263ad30ca1aa70d24ae53b31a72b0041f1a1846a70a8873015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
